export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_BOOKINGS: 'VIEW_BOOKINGS',
  MANAGE_BOOKINGS: 'MANAGE_BOOKINGS',
  VIEW_GUESTS: 'VIEW_GUESTS',
  MANAGE_GUESTS: 'MANAGE_GUESTS',
  VIEW_ROOMS: 'VIEW_ROOMS',
  MANAGE_ROOMS: 'MANAGE_ROOMS',
  VIEW_FINANCIAL: 'VIEW_FINANCIAL',
  MANAGE_FINANCIAL: 'MANAGE_FINANCIAL',
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  MANAGE_STAFF: 'MANAGE_STAFF',
} as const;

export type Permission = keyof typeof PERMISSIONS;

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  owner: Object.values(PERMISSIONS),
  manager: Object.values(PERMISSIONS),
  staff: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.MANAGE_BOOKINGS,
    PERMISSIONS.VIEW_GUESTS,
    PERMISSIONS.VIEW_ROOMS,
  ],
};